In [22]:
# Assigning function to a variable
def greet():
    print("Hello! I'm learning Python.")

say_hello = greet  # Assigning function to another variable
say_hello()


Hello! I'm learning Python.


In [23]:

# Passing function as an argument
def add(x, y):
    return x + y

def operate(func, a, b):
    return func(a, b)

result = operate(add, 2, 3)
print(result)  # Output: 5

5


In [24]:
# Returning a function from another function
def multiplier(factor):
    def multiply(num):
        return num * factor
    return multiply

double = multiplier(2)  # Creating a function that doubles a number
print(double(5))  # Output: 10

10


In [25]:

# Recursive function
def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n - 1)

print(factorial(5))  # Output: 120

120


In [26]:
# Using docstrings
def calculator(values):
    """This function performs calculations."""
    pass

help(calculator)

Help on function calculator in module __main__:

calculator(values)
    This function performs calculations.



In [27]:
# Local and Global Variables

def add_numbers():
    a, b = 10, 20  # Local variables
    print(f"Sum: {a + b}")

add_numbers()

Sum: 30


In [28]:
# Global variable usage
a, b = 10, 20

def sum_numbers():
    print(f"Sum: {a + b}")

sum_numbers()


Sum: 30


In [29]:
# Modifying global variable
a = 10

def modify_global():
    global a
    a = 20
    print(f"Modified Sum: {a + b}")

modify_global()

Modified Sum: 40


In [30]:
# Using nonlocal variables
def outer():
    x = 5
    def inner():
        nonlocal x
        x = 10
    inner()
    print("Updated x:", x)

outer()

Updated x: 10


In [31]:
# NumPy Basics
import numpy as np

# Creating lists and NumPy arrays
py_list = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])
print(type(py_list))  # Output: <class 'list'>
print(type(numpy_array))  # Output: <class 'numpy.ndarray'>

# 1D and 2D arrays
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print("Dimensions:", arr_2d.ndim)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Dimensions: 2


In [32]:
# Arrays filled with specific values
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
fixed_array = np.full((2, 3), 8)
print(zeros_array)
print(ones_array)
print(fixed_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]]


In [33]:

# Creating arrays with evenly spaced values
linspace_array = np.linspace(1, 10, 5)
print(linspace_array)

[ 1.    3.25  5.5   7.75 10.  ]


In [34]:
# Creating arrays with a range of numbers
range_array = np.arange(1, 10, 5)
print(range_array)



[1 6]


In [35]:
# Generating random arrays
random_array = np.random.rand(3, 3)  # Values between 0 and 1
print(random_array)

random_int_array = np.random.randint(1, 100, (3, 3))
print(random_int_array.ndim)



[[0.87325895 0.52496493 0.34842923]
 [0.05192051 0.90926799 0.64674822]
 [0.97686857 0.91165799 0.34321295]]
2


In [36]:
# Shape, size, and dimensions of arrays
arr = np.array([[1, 2, 3], [3, 4, 5]])
print("Shape:", arr.shape)
print("Size:", arr.size)



Shape: (2, 3)
Size: 6


In [37]:
# Reshaping arrays
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape((2, 3))
print(arr_reshaped)


[[1 2 3]
 [4 5 6]]


In [38]:
# Element-wise addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)



[5 7 9]


In [39]:
# Min, max, and sum operations
arr = np.array([[1, 2, 3], [3, 4, 5]])
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Sum:", np.sum(arr))



Max: 5
Min: 1
Sum: 18


In [40]:
# Array indexing and slicing
arr = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print("Last element:", arr[-1, -1])
print("Sliced array:", arr[:, 1:3])



Last element: 6
Sliced array: [[2 3]
 [4 5]
 [5 6]]


In [41]:
# Conditional filtering
arr1 = np.array([1, 2, 3])
result = np.where(arr1 > 10)
print(result)



(array([], dtype=int64),)


In [42]:
# Modifying array elements
arr1 = np.array([1, 2, 3])
np.put(arr1, [0, 1], [10, 20])
print(arr1)

[10 20  3]
